# Generated by Django 3.2.9 on 2021-12-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
    ]
